CREATE SCHEMA health_care_v1_dev AUTHORIZATION DBA;

CREATE TABLE health_care_v1_dev.company (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE health_care_v1_dev.agency_type (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  name VARCHAR(255) NOT NULL,
  status INT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE health_care_v1_dev.agency (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  agency_type_id INT NOT NULL,
  company_id INT NOT NULL,
  company_id1 INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (agency_type_id) REFERENCES health_care_v1_dev.agency_type (id),
  FOREIGN KEY (company_id1) REFERENCES health_care_v1_dev.company (id)
);

CREATE TABLE health_care_v1_dev.user (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE health_care_v1_dev.review (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
  user_id INT NOT NULL,
  employee_id INT NOT NULL,
  affect_start DATETIME DEFAULT NULL,
  affect_end DATETIME DEFAULT NULL,
  content INT DEFAULT '0' NULL,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
--   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
  user_id1 INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES health_care_v1_dev.user (id),
  FOREIGN KEY (user_id1) REFERENCES health_care_v1_dev.user (id),
);
